<option></option>
<option value="1">1. Франция - ns1.ihtier.net</option>
<option value="2">2. Франция - сервер доступен дилерам </option>
<option value="3">3. Франция - сервер доступен дилерам </option>
<option value="4">4. Tajikistan - сервер доступен дилерам </option>
<option value="5">5. Франция - ns5.ihtier.net </option>
<option value="6">6. Франсия - сервер доступен дилерам </option>
<option value="7">7. Украина - ns7.ihtier.net </option>
<option value="8">8. Turkmen - сервер доступен дилерам </option>
<option value="9">9. Turkmen - сервер доступен дилерам </option>
<option value="10">10. Россия - сервер доступен дилерам </option>
<option value="11">11. Россия - сервер доступен дилерам </option>
<option value="12">12. Россия - сервер доступен дилерам </option>
<option value="13">13. Tajikistan - сервер доступен дилерам </option>
<option value="14">14. Россия - сервер доступен дилерам </option>
<option value="15">15. Росcия - сервер доступен дилерам </option>
<option value="16">16. Tajikistan - сервер доступен дилерам </option>
<option value="17">17. Франция - ns17.ihtier.net </option>
<option value="18">18. Франция - сервер доступен дилерам </option>
<option value="19">19. Франция - сервер доступен дилерам </option>
<option value="20">20. Франция - сервер доступен дилерам </option>
<option value="21">21. Россия - сервер доступен дилерам </option>
<option value="22">22. Германия - сервер доступен дилерам </option>
<option value="23">23. Россия - сервер доступен дилерам </option>
<option value="24">24. Tajikistan - сервер доступен дилерам </option>
<option value="25">25. Tajikistan - сервер доступен дилерам </option>
<option value="26">26. Россия - сервер доступен дилерам </option>
<option value="27">27. Tajikistan - сервер доступен дилерам </option>
<option value="28">28. Россия - сервер доступен дилерам </option>
<option value="29">29. Россия - сервер доступен дилерам </option>
<option value="30">30. Россия - сервер доступен дилерам </option>
<option value="31">31. Россия - сервер доступен дилерам </option>
<option value="32">32. Turkmen - сервер доступен дилерам </option>
<option value="33">33. Turkmen - сервер доступен дилерам </option>
<option value="34">34. Turkmen - сервер доступен дилерам </option>
<option value="35">35. Turkmen - сервер доступен дилерам </option>
<option value="36">36. Turkmen - сервер доступен дилерам </option>
